import turtle
import random

screen = turtle.Screen()
screen.screensize(500, 500)
screen.bgcolor("lightcoral")
t = turtle.Turtle()
t.speed(0)
t.hideturtle()

# intro screen
t.penup()
t.goto(0, 0)
t.pendown()
t.write("All About Me", font=("Georgia", 30, "bold"), align="center")

t.penup()
t.goto(-25,200)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.pencolor("red")
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

t.penup()
t.goto(-200, 200)
t.pendown()
screen.addshape("yellow.gif")
t.shape("yellow.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(150, -200)
t.pendown()
screen.addshape("minons.gif")
t.shape("minons.gif")
t.stamp()
t.shape("classic")

round = input("Press enter to continue: ")

# 2nd screen
t.clear()
screen.bgcolor("lightblue")
t.penup()
t.goto(0, 250)
t.pendown()
t.pencolor("black")
t.write("My Favorite Foods", font=("Georgia", 30, "bold"), align="center")
t.penup()
t.goto(0, 150)
t.pendown()
t.write("1) Chicken Alfredo", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(-200, 150)
t.pendown()
screen.addshape("Alfredo.gif")
t.shape("Alfredo.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0, 100)
t.pendown()
t.write("2) Buldak Ramen", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(0, -70)
t.pendown()
screen.addshape("ramen.gif")
t.shape("ramen.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0, 50)
t.pendown()
t.write("3) Ice Cream", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(200, 150)
t.pendown()
screen.addshape("ice.gif")
t.shape("ice.gif")
t.stamp()
t.shape("classic")

# circle
t.penup()
t.goto(0, -300)
t.pendown()
t.pendown()
t.pencolor("hotpink")
t.fillcolor("hotpink")
t.begin_fill()
t.circle(50)
t.end_fill()

round = input("Press enter to continue: ")

# 3rd screen
t.clear()
screen.bgcolor("mediumpurple")
t.pencolor("black")
t.penup()
t.goto(0, 250)
t.pendown()
t.write("My Hobbies", font=("Georgia", 30, "bold"), align="center")
t.penup()
t.goto(-150, 100)
t.pendown()
t.write("1) Dance", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(-150, 50)
t.pendown()
screen.addshape("dance.gif")
t.shape("dance.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(150, 100)
t.pendown()
t.write("2) Painting", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(-150, -100)
t.pendown()
t.write("3) Shopping", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(-150, -175)
t.pendown()
screen.addshape("shopping.gif")
t.shape("shopping.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(150, -100)
t.pendown()
t.write("4) Reading", font=("Georgia", 15, "bold"), align="center")

# triangle
t.setheading(0)
t.penup()
t.goto(0,0)
t.pendown()
t.pencolor("paleturquoise")
t.fillcolor("paleturquoise")
t.begin_fill()
t.forward(100)
t.goto(0,100)
t.goto(-100,0)
t.end_fill()

round = input("Press enter to continue: ")

# 4th screen
t.clear()
screen.bgcolor("papayawhip")
t.pencolor("black")
t.penup()
t.goto(0, 250)
t.pendown()
t.write("Favorite Movie", font=("Georgia", 30, "bold"), align="center")
t.penup()
t.goto(0, 150)
t.pendown()
t.write("'To All the Boys I've Loved Before'", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(0, 50)
t.pendown()
screen.addshape("movie.gif")
t.shape("movie.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0, -100)
t.pendown()
screen.addshape("lara.gif")
t.shape("lara.gif")
t.stamp()
t.shape("classic")

# flower
t.penup()
t.goto(-200,0)
t.pendown()
t.pencolor("green")
t.pensize(8)
t.goto(-200,-100)
t.pensize(1)

t.penup()
t.goto(-200,0)
t.pendown()

t.pencolor("pink")
t.fillcolor("pink")
t.begin_fill()
t.circle(25)
t.setheading(90)
t.circle(25)
t.setheading(180)
t.circle(25)
t.setheading(270)
t.circle(25)
t.end_fill()

t.penup()
t.goto(-200,-15)
t.pendown()
t.setheading(0)
t.fillcolor("yellow")
t.begin_fill()
t.circle(15)
t.end_fill()

round = input("Press enter to continue: ")

# 5th screen
t.clear()
screen.bgcolor("mediumseagreen")
t.pencolor("black")
t.penup()
t.goto(0, 250)
t.pendown()
t.write("Favorite Sport", font=("Georgia", 30, "bold"), align="center")
t.penup()
t.goto(0, 150)
t.pendown()
t.write("Basketball", font=("Georgia", 15, "bold"), align="center")
t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape("basketball.gif")
t.shape("basketball.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0, -200)
t.pendown()
screen.addshape("game.gif")
t.shape("game.gif")
t.stamp()
t.shape("classic")

# rhombus
t.penup()
t.goto(-150,200)
t.pendown()
t.setheading(135)
t.pencolor("lightyellow")
t.fillcolor("lightyellow")
t.begin_fill()
t.speed(1)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

turtle.done()